In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("./knn2.csv")
print(df)
x_train= np.array(df.iloc[:, 1:-1])
print(f"xtrain: \n{x_train}")
y_train= np.array(df.iloc[:, -1])
print(f"ytrain: \n{y_train}")
test = np.array([[7,7]])
print(f"test :\n {test}")
def knn1_layer(x_train, y_train, x_test):
    w = np.array( [[-5, 15]])
    b= -4
    a=0
    k=0
    m= len(x_train)
    while True:
        d= True
        k+=1
        print(f"lần lặp thứ {k}")
        for i in range(m):
            x= x_train[i]
            n= w.dot(x.T) +b
            if n < 0:
                a=0
            else:
                a=1
            if a != y_train[i]:
                e = y_train[i]-a
                w = w+np.dot(e, x)
                b+=e
                d= False
        print(f"w= {w}")
        print(f"b= {b}")
        if d:
            break
    n= w.dot(test.T) +b
    if n<0:
        wr ="sản phẩm đạt yêu cầu\n"
    else:
        wr="sản phẩm đạt yêu cầu\n"
    print(f"sản phẩm test : {wr}")

   STT  chay  sut  loai
0    1     8    8     1
1    2    10    8     1
2    3     9    8     1
3    4     8    7     1
4    5     9    7     1
5    6     2    2     0
6    7     3    3     0
7    8     1    3     0
8    9     1    2     0
9   10     2    3     0
xtrain: 
[[ 8  8]
 [10  8]
 [ 9  8]
 [ 8  7]
 [ 9  7]
 [ 2  2]
 [ 3  3]
 [ 1  3]
 [ 1  2]
 [ 2  3]]
ytrain: 
[1 1 1 1 1 0 0 0 0 0]
test :
 [[7 7]]
lần lặp thứ 1
w= [[-11   7]]
b= -7
lần lặp thứ 2
w= [[-9  7]]
b= -9
lần lặp thứ 3
w= [[-7  7]]
b= -11
lần lặp thứ 4
w= [[-5  7]]
b= -13
lần lặp thứ 5
w= [[-3  4]]
b= -16
lần lặp thứ 6
w= [[-1  4]]
b= -18
lần lặp thứ 7
w= [[-1  4]]
b= -18
sản phẩm test : sản phẩm đạt yêu cầu

