In [1]:
import numpy as np

In [4]:
def read_file(filename_name):    
    with open(filename_name, 'r') as f:
        x_train=[]
        while True:
            line = f.readline()
            if not line: break
            x_train.append(line.split())
        return np.array(x_train)

In [30]:
def get_label(X_train, x_test, labels):
    distances = [np.sqrt(np.sum((x_test - x_train)**2)) for x_train in X_train]
    nearist = np.argsort(distances)[0]
    return str(labels[nearist])

In [23]:
if __name__ == '__main__':
    X_train = read_file('./kddcup.data')
    label = X_train[:, -1]
    X_train = X_train[:, 4:-1].astype(np.float64)
    x_test = read_file('./kddcup.test')
    label_test = x_test[:, -1]
    x_test = x_test[:, 4:-1].astype(np.float64)
    print(X_train)

[[ 181. 5450.    0. ...    0.    0.    0.]
 [ 239.  486.    0. ...    0.    0.    0.]
 [ 235. 1337.    0. ...    0.    0.    0.]
 ...
 [1032.    0.    0. ...    0.    0.    0.]
 [1032.    0.    0. ...    0.    0.    0.]
 [1032.    0.    0. ...    0.    0.    0.]]


In [26]:
print(label_test)

['normal.' 'normal.' 'normal.' 'normal.' 'normal.' 'smurf.' 'smurf.'
 'smurf.' 'smurf.' 'smurf.' 'neptune.' 'neptune.' 'neptune.' 'neptune.'
 'neptune.']


In [31]:
print(list(get_label(X_train, x, label) for x in x_test))

['normal.', 'normal.', 'normal.', 'normal.', 'normal.', 'smurf.', 'smurf.', 'smurf.', 'smurf.', 'smurf.', 'neptune.', 'neptune.', 'neptune.', 'neptune.', 'neptune.']
